version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 290917
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress-user
      MYSQL_PASSWORD: 290917

  wordpress:
    depends_on:
      - db
    build: .
    ports:
      - '80:80'
    restart: always
    volumes:
      - .:/var/www/html/wp-content/themes/ache-theme
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress-user
      WORDPRESS_DB_PASSWORD: 290917
volumes:
  db_data:
